// Code generated by thriftgo (0.4.3). DO NOT EDIT.

package order

import (
	"context"
	"fmt"
)

type OrderItem struct {
	OrderId string `thrift:"order_id,1" frugal:"1,default,string" json:"order_id"`
	Amount  int32  `thrift:"amount,2" frugal:"2,default,i32" json:"amount"`
}

func NewOrderItem() *OrderItem {
	return &OrderItem{}
}

func (p *OrderItem) InitDefault() {
}

func (p *OrderItem) GetOrderId() (v string) {
	return p.OrderId
}

func (p *OrderItem) GetAmount() (v int32) {
	return p.Amount
}
func (p *OrderItem) SetOrderId(val string) {
	p.OrderId = val
}
func (p *OrderItem) SetAmount(val int32) {
	p.Amount = val
}

func (p *OrderItem) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderItem(%+v)", *p)
}

var fieldIDToName_OrderItem = map[int16]string{
	1: "order_id",
	2: "amount",
}

type GetOrdersRequest struct {
	UserId string `thrift:"user_id,1" frugal:"1,default,string" json:"user_id"`
}

func NewGetOrdersRequest() *GetOrdersRequest {
	return &GetOrdersRequest{}
}

func (p *GetOrdersRequest) InitDefault() {
}

func (p *GetOrdersRequest) GetUserId() (v string) {
	return p.UserId
}
func (p *GetOrdersRequest) SetUserId(val string) {
	p.UserId = val
}

func (p *GetOrdersRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetOrdersRequest(%+v)", *p)
}

var fieldIDToName_GetOrdersRequest = map[int16]string{
	1: "user_id",
}

type GetOrdersResponse struct {
	UserId string       `thrift:"user_id,1" frugal:"1,default,string" json:"user_id"`
	Orders []*OrderItem `thrift:"orders,2" frugal:"2,default,list<OrderItem>" json:"orders"`
}

func NewGetOrdersResponse() *GetOrdersResponse {
	return &GetOrdersResponse{}
}

func (p *GetOrdersResponse) InitDefault() {
}

func (p *GetOrdersResponse) GetUserId() (v string) {
	return p.UserId
}

func (p *GetOrdersResponse) GetOrders() (v []*OrderItem) {
	return p.Orders
}
func (p *GetOrdersResponse) SetUserId(val string) {
	p.UserId = val
}
func (p *GetOrdersResponse) SetOrders(val []*OrderItem) {
	p.Orders = val
}

func (p *GetOrdersResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetOrdersResponse(%+v)", *p)
}

var fieldIDToName_GetOrdersResponse = map[int16]string{
	1: "user_id",
	2: "orders",
}

type OrderService interface {
	GetOrders(ctx context.Context, req *GetOrdersRequest) (r *GetOrdersResponse, err error)
}

type OrderServiceGetOrdersArgs struct {
	Req *GetOrdersRequest `thrift:"req,1" frugal:"1,default,GetOrdersRequest" json:"req"`
}

func NewOrderServiceGetOrdersArgs() *OrderServiceGetOrdersArgs {
	return &OrderServiceGetOrdersArgs{}
}

func (p *OrderServiceGetOrdersArgs) InitDefault() {
}

var OrderServiceGetOrdersArgs_Req_DEFAULT *GetOrdersRequest

func (p *OrderServiceGetOrdersArgs) GetReq() (v *GetOrdersRequest) {
	if !p.IsSetReq() {
		return OrderServiceGetOrdersArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *OrderServiceGetOrdersArgs) SetReq(val *GetOrdersRequest) {
	p.Req = val
}

func (p *OrderServiceGetOrdersArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *OrderServiceGetOrdersArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderServiceGetOrdersArgs(%+v)", *p)
}

var fieldIDToName_OrderServiceGetOrdersArgs = map[int16]string{
	1: "req",
}

type OrderServiceGetOrdersResult struct {
	Success *GetOrdersResponse `thrift:"success,0,optional" frugal:"0,optional,GetOrdersResponse" json:"success,omitempty"`
}

func NewOrderServiceGetOrdersResult() *OrderServiceGetOrdersResult {
	return &OrderServiceGetOrdersResult{}
}

func (p *OrderServiceGetOrdersResult) InitDefault() {
}

var OrderServiceGetOrdersResult_Success_DEFAULT *GetOrdersResponse

func (p *OrderServiceGetOrdersResult) GetSuccess() (v *GetOrdersResponse) {
	if !p.IsSetSuccess() {
		return OrderServiceGetOrdersResult_Success_DEFAULT
	}
	return p.Success
}
func (p *OrderServiceGetOrdersResult) SetSuccess(x interface{}) {
	p.Success = x.(*GetOrdersResponse)
}

func (p *OrderServiceGetOrdersResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *OrderServiceGetOrdersResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderServiceGetOrdersResult(%+v)", *p)
}

var fieldIDToName_OrderServiceGetOrdersResult = map[int16]string{
	0: "success",
}
